# Generated by Django 5.2.6 on 2025-11-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('ProductId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('BatchNo', models.CharField(max_length=45, null=True)),
                ('SafeStock', models.IntegerField(null=True)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
                ('Location', models.CharField(max_length=20, null=True)),
                ('ExpiryDate', models.DateTimeField(null=True)),
                ('PhotoLocation', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrdersID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Notes', models.TextField(null=True)),
                ('Status', models.IntegerField()),
                ('CustomerID', models.CharField(max_length=45, null=True)),
                ('Priority', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemNo', models.IntegerField()),
                ('OrderNo', models.CharField(max_length=45)),
                ('ProductSKU', models.CharField(max_length=45)),
                ('Quantity', models.IntegerField()),
                ('Remark', models.CharField(max_length=45, null=True)),
                ('OutOfStock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('SKU', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('VCodeName', models.CharField(max_length=45, null=True)),
                ('ProductName', models.CharField(max_length=45, null=True)),
                ('Unit', models.CharField(max_length=45, null=True)),
                ('Category', models.CharField(max_length=45, null=True)),
                ('Status', models.IntegerField()),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('Colour', models.CharField(max_length=20, null=True)),
                ('ShelfOArea', models.CharField(max_length=45, null=True)),
                ('Vendor', models.CharField(max_length=45, null=True)),
                ('PhotoProduct', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
